site_name: Cocoon Dev Team

plugins: []
copyright: Copyright &copy; 2024 Cocoon Dev Team

theme:
  name: material
  font: false
  language: zh
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.tracking
  palette:
    - scheme: default
      primary: blue
      accent: deep orange
    - scheme: slate
      accent: deep purple

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
     emoji_index: !!python/name:pymdownx.emoji.twemoji
     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true

extra:
  generator: false